#!/bin/bash
version='1.6.1'

killall webcord &>/dev/null && echo "Closing Discord first..."

install_packages "https://github.com/SpacingBat3/WebCord/releases/download/v${version}/webcord_${version}_armhf.deb" || exit 1

#change this to true to brand Webcord as Discord
if false;then
  sudo sed -i 's/Name=.*/Name=Discord/g' /usr/share/applications/webcord.desktop

  sudo cp -f "$(dirname "$0")/icon-64.png" /usr/share/pixmaps/webcord.png
  sudo cp -f "$(dirname "$0")/icon-64.png" /usr/lib/webcord/resources/app.png
fi

exit 0
