#!/bin/bash
if [ ! -e ~/box64 ];then
  echo "The $HOME/box64 folder does not exist. Nothing to do!"
  exit 0
fi
cd ~/box64/build || error "Failed to enter ~/box64/build!"
sudo make uninstall || error "Failed to uninstall box64!"
rm -rf ~/box64 || error "Failed to delete the $HOME/box64 directory!"

