#!/bin/bash
#Remove any qemu packages first to prevent conflicting packages
sudo apt purge -yqq qemu* &>/dev/null
rm -f ~/qemu.deb
#Download QEMU
wget -O ~/qemu.deb https://github.com/chunky-milk/qemu-arm-builds/releases/download/6.0.50/qemu-6.0.50-arm64.deb || error 'Failed to Download QEMU!'

#Install QEMU
install_packages $HOME/qemu.deb || error 'Failed to install qemu.deb!'
rm -f ~/qemu.deb
