#!/bin/bash
install_packages g++ cmake make ninja-build libsdl2-dev libogg-dev libvorbis-dev libopenal-dev libalut-dev libfreetype6-dev || exit 1

#download
cd ~/.local/share
rm -rf $(pwd)/master.zip $(pwd)/astromenace/
wget -O $(pwd)/master.zip https://github.com/viewizard/astromenace/archive/refs/heads/master.zip || error 'Failed to download zip!'
unzip $(pwd)/master.zip -D $(pwd)/astromenace || error 'Failed to extract'
rm -f $(pwd)/master.zip
#build
cd $(pwd)/astromenace/
cmake . || error 'Failed to run cmake'
c=nproc
make || error 'Failed to run make'

#menu button
echo "[Desktop Entry]
Version=1.1
Type=Application
Name=AstroMenace
Comment=Hardcore 3D space scroll-shooter with spaceship upgrade possibilities.
Icon=$(pwd)/share/astromenace_128.png
Exec=$(pwd)/astromenace
Categories=Game;
Terminal=false
StartupNotify=true" > ~/.local/share/applications/astromenace.desktop

