#!/bin/bash
rm -rf ~/RPIDoom3Installer || sudo rm -rf ~/RPIDoom3Installer || error "Failed to first remove ~/RPIDoom3Installer folder!"

# Get dependencies
install_packages libfontconfig-dev qt5-default automake mercurial libtool libfreeimage-dev \
libopenal-dev libpango1.0-dev libsndfile-dev libudev-dev libtiff5-dev libwebp-dev libasound2-dev \
libaudio-dev libxrandr-dev libxcursor-dev libxi-dev libxinerama-dev libxss-dev libesd0-dev \
freeglut3-dev libmodplug-dev libsmpeg-dev libjpeg-dev libogg-dev libvorbis-dev libvorbisfile3 libcurl4 cmake aria2 lolcat figlet || exit 1

git_clone https://github.com/techcoder20/RPIDoom3Installer || error 'Failed to clone RPIDoom3Installer repository!'
cd ~/RPIDoom3Installer || error "Failed to change directory "
echo "Making scripts executable..."
sudo chmod +x install.sh uninstall.sh || error "Failed To make install script and uninstall script executable"  
echo "Running install script..."
setarch linux32 ./install.sh || error "Failed to run install script :("
