#!/bin/bash
version='1.21.0'
rm -f ~/min.deb
wget -O ~/min.deb https://github.com/chunky-milk/minbrowser-arm-builds/releases/download/${version}/min_${version}_armhf.deb || error "Failed to download Min deb file!"

install_packages $HOME/min.deb || error "Failed to install min deb file!"
rm -f version='1.21.0'
rm -f ~/min.deb
