#!/bin/bash
install_packages libnss3:armhf libnm0:armhf libdbus-glib-1-2:armhf libudev1:armhf libnspr4:armhf libgudev-1.0-0:armhf libusb-1.0-0:armhf libappindicator1:armhf || exit 1

if dpkg -l steam-devices ;then
  echo "Removing steam-devices package because it conflicts with steam-launcher..."
  sudo apt purge -y steam-devices
fi
if dpkg -l steamlink ;then
  echo "Removing steamlink package because it conflicts with steam-launcher..."
  sudo apt purge -y steamlink
fi
"${DIRECTORY}/manage" install-if-not-installed Box86 || error "Box86 failed to install somehow!"

echo "Downloading steam.deb"
wget https://steamcdn-a.akamaihd.net/client/installer/steam.deb || error "Failed to download steam.deb!"
"${DIRECTORY}/api" apt_lock_wait
sudo dpkg -i ~/steam.deb || error "dpkg failed to install steam.deb!"
rm ~/steam.deb

echo "Editing steam script to run on Raspberry Pi..."
sudo sed -i 's/set -e/set -e\nexport STEAMOS=1\nexport STEAM_RUNTIME=1\nBOX86_NOGTK=1/' /usr/lib/steam/bin_steam.sh
echo "Creating a Steam config file so it will launch in Small Mode..."
mkdir -p ~/.local/share/Steam/config
wget https://raw.githubusercontent.com/Botspot/Steam-RPi/main/DialogConfig.vdf -O ~/.local/share/Steam/config/DialogConfig.vdf

exit 0
