#!/bin/bash
rm -f ~/puffin.deb
wget -O ~/puffin.deb https://download.puffinbrowser.com/linux/raspbian/puffin-internet-terminal-demo_8.2.4.705_armhf.deb || error "Failed to download puffin-internet-terminal.deb!"
install_packages ~/puffin.deb || error "APT failed to install puffin-internet-terminal.deb!"

rm -f ~/puffin.deb

