#!/bin/bash
wget -O ~/veracrypt.deb 'https://sourceforge.net/projects/veracrypt/files/VeraCrypt%201.24-Update7/veracrypt-1.24-Update7-Debian-10-armhf.deb/download' || error "Failed to download veracrypt.deb!"

install_packages $HOME/veracrypt.deb || error "Failed to install veracrypt.deb!"

rm -f ~/veracrypt.deb
