#!/bin/bash
rm -f ~/vivaldi.deb
wget -O ~/vivaldi.deb https://downloads.vivaldi.com/stable/vivaldi-stable_4.1.2369.21-1_armhf.deb || error 'Failed to download vivaldi!'
install_packages $HOME/vivaldi.deb || error 'Failed to install vivaldi.deb!'
rm -f ~/vivaldi.deb
