#!/bin/bash
# Get dependencies
install_packages python3 python3-pip fonts-powerline fonts-fantasque-sans || exit 1
wget -qO- https://raw.githubusercontent.com/techcoder20/RPI-PowerlineShell-Installer/main/install.sh | bash || error "install.sh failed!"

