#!/bin/bash
#Defining Variables
name=pycharm-community
purge_packages || exit 1

echo "Deleting /opt/$name directory"
sudo rm -rf /opt/$name || error "Failed to delete /opt/$name directory"
rm -f ~/.local/share/applications/jetbrains-pycharm-ce.desktop
