#!/bin/bash
rm -f ~/remarkable.deb
wget -O ~/remarkable.deb https://remarkableapp.github.io/files/remarkable_1.87_all.deb || error 'Failed to download remarkable.deb!'
install_packages $HOME/remarkable.deb || error "Failed to install ~/remarkable.deb!"
rm -f ~/remarkable.deb
