#!/bin/bash

purge_packages || exit 1
sudo systemctl stop WebStationSYSMON.service || error "Failed to stop sysmon service!"
sudo systemctl disable WebStationSYSMON.service || error "Failed to disable sysmon service!"
sudo systemctl daemon-reload || error "Failed to run systemctl daemon-reload!"
sudo rm -rf /opt/sysmon
