#!/bin/bash

wget -O ~/hfs.exe https://www.rejetto.com/hfs/hfs.exe || exit 1

"${DIRECTORY}/manage" install-if-not-installed 'Wine (x86)' || error "Wine is required to run HTTPS File Server but it failed to install!"

mkdir -p ~/.local/share/applications
echo "[Desktop Entry]
Type=Application
Version=1.0
Name=HTTPS File Server
Exec=wine $HOME/hfs.exe
Comment=Simple file sharing webserver
Icon=$(dirname "$0")/icon-64.png
Categories=Network;
StartupNotify=true" > ~/.local/share/applications/hfs.desktop
