#!/bin/bash
wget -O ~/sonic-pi.deb https://sonic-pi.net/files/releases/v3.3.1/sonic-pi_3.3.1_1_armhf.deb || error "Failed to download deb file!"

install_packages $HOME/sonic-pi.deb libconfig9 xcompmgr || exit 1

rm -f sonic-pi_3.2.2_4_armhf.deb

exit 0
