#!/bin/bash
# Download teamviewer installation file
rm -f ~/teamviewer-host_armhf.deb
wget -O ~/teamviewer-host_armhf.deb https://download.teamviewer.com/download/linux/teamviewer-host_armhf.deb || error "Failed to download teamviewer-host_armhf.deb"

#install deb file
install_packages $HOME/teamviewer-host_armhf.deb || error "Failed to install teamviewer-host_armhf.deb"
# Delete teamviewer installation file
rm -f ~/teamviewer-host_armhf.deb
