#!/bin/bash
VERSION=arduino-1.8.15

cd ~/.local/share
rm -f $(pwd)/$VERSION-linuxaarch64.tar.xz
wget https://downloads.arduino.cc/$VERSION-linuxaarch64.tar.xz || error "failed to download!"

tar -xf $(pwd)/$VERSION-linuxaarch64.tar.xz || error "failed to extract with tar!"
$(pwd)/$VERSION/install.sh || error "failed to run install as $USER user!"
sudo $(pwd)/$VERSION/install.sh || error "failed run install as root user!"

rm -f $HOME/Desktop/arduino-arduinoide.desktop $(pwd)/$VERSION-linuxaarch64.tar.xz
exit 0
