#!/bin/bash
rm -f ~/timeshift.deb
wget -O ~/timeshift.deb https://github.com/teejee2008/timeshift/releases/download/v20.11.1/timeshift_20.11.1_armhf.deb || error 'Failed to download timeshift!'
install_packages $HOME/timeshift.deb || error 'Failed to install .deb file!'
rm -f ~/timeshift.deb
