#!/bin/bash

install_packages yad xclip expect || exit 1

git_clone https://github.com/Botspot/cloudbuddy || error "Failed to clone CloudBuddy repository!"

status "Running CloudBuddy setup script..."
~/cloudbuddy/main.sh setup || error "CloudBuddy setup script failed!"
