#!/bin/bash
wget https://github.com/Pi-Apps-Coders/files/raw/main/lightpad_0.0.8rev1_arm64.deb -O ~/lightpad.deb || error "Failed to download lightpad.deb!"

install_packages $HOME/lightpad.deb || error 'Failed to install lightpad.deb'

rm -f ~/lightpad.deb

echo "[Desktop Entry]
Version=1.0
Type=Application
Name=Lightpad
Icon=lightpad
Exec=com.github.libredeb.lightpad
Comment=LightPad is a lightweight, simple and powerful application launcher
Categories=Accessories;Utility;
Terminal=false" > ~/.local/share/applications/lightpad.desktop

