#!/bin/bash
# Get dependencies
install_packages build-essential qmlscene qt5-qmake qt5-default qtdeclarative5-dev qml-module-qtquick-controls qml-module-qtgraphicaleffects qml-module-qtquick-dialogs qml-module-qtquick-localstorage qml-module-qtquick-window2 qml-module-qt-labs-settings qml-module-qt-labs-folderlistmodel || exit 1
# Get CRT from github
git_clone --recursive https://github.com/Swordfish90/cool-retro-term || error "failed to clone repository!"
# Compile
cd cool-retro-term || error "failed on cd step!"
qmake || error "failed on qmake step!"
make -j8 || error "failed on make step!"
cp -rf qmltermwidget/src/qmldir qmltermwidget/lib/kb-layouts qmltermwidget/lib/color-schemes qmltermwidget/src/QMLTermScrollbar.qml qmltermwidget/QMLTermWidget

echo "[Desktop Entry]
Comment=Use the command line the old way
Exec=$HOME/cool-retro-term/cool-retro-term
GenericName=Terminal emulator
Icon=$HOME/cool-retro-term/app/icons/64x64/cool-retro-term.png
Name=Cool Retro Term
Categories=GTK;System;TerminalEmulator;
StartupNotify=true
Terminal=false
Type=Application
Keywords=shell;prompt;command;commandline;console;command line;execute;" > ~/.local/share/applications/crt.desktop
