#!/bin/bash
rm -f ~/.local/share/applications/minecraft.desktop
sudo rm -rf ~/Minecraft
sudo rm -rf ~/lwjgl2arm32
sudo rm -rf ~/lwjgl3arm32
sudo rm -rf ~/lwjgl3arm64
sudo rm -rf ~/lwjgl2arm64
sudo rm -rf /usr/share/minecraftjava/
sudo rm -rf /opt/jdk-16.0.1+9 || sudo rm -rf /opt/jdk-16.0.1+4
