#!/bin/bash
install_packages  adb ffmpeg libsdl2-2.0-0 python3-pip python3-tk gcc git pkg-config meson ninja-build libavcodec-dev libavformat-dev libavutil-dev libsdl2-dev || exit 1

wget -O ~/scrcpy.tar.gz https://misapuntesde.com/rpi_share/scrcpy-1.13.tar.gz || exit 1
tar -xf scrcpy.tar.gz || exit 1
rm scrcpy-1.13.tar.gz

ln -s /usr/bin/adb $HOME/scrcpy/

sudo mkdir -p /usr/local/share/scrcpy
sudo cp -af $HOME/scrcpy/scrcpy-server /usr/local/share/scrcpy/scrcpy-server
rm -rf ~/droidbuddy
git_clone https://gitlab.com/gazlene/droidbuddy.git || exit 1
sudo pip3 install Pillow || exit 1

mkdir -p ~/.local/share/applications
echo "[Desktop Entry]
Name=AndroidBuddy
Comment=GUI for Android device recovery and maintainence
Icon=$(dirname "$0")/icon-64.png
Exec=bash -c 'cd $HOME/droidbuddy ; python3 main.py'
Type=Application
Encoding=UTF-8
Terminal=false
Categories=Utility;" > ~/.local/share/applications/androidbuddy.desktop
