#!/bin/bash
if dpkg -l box86 &>/dev/null ;then
  sudo apt purge -y box86
fi
sudo rm -f /etc/apt/sources.list.d/box86.list
sudo dpkg --add-architecture armhf

install_packages cmake make gcc-arm-linux-gnueabihf python3 gcc libc6-dev g++ build-essential || exit 1

rm -rf ~/box86
git_clone https://github.com/ptitSeb/box86
cd box86
mkdir build; cd build; cmake .. -DRPI4ARM64=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo
#determine how many threads can run without running out of memory
if [ $(($(free -bt | tail -1 | awk '{print $2}')-$(free -bt | tail -1 | awk '{print $3}'))) -le 2000000000 ];then
  #less than 2GB of available ram
  threads=3
else
  #greater than 2GB of available ram
  threads=5
fi
echo "Compiling Box64 with $threads threads..."
make -j${threads} || error 'Failed to compile'
sudo make install || error "Failed to run 'sudo make install'!"

if ! sudo systemctl restart systemd-binfmt ;then
  echo -e "\nWarning: systemd-binfmt failed to restart. Getting debug info..."
  echo "Running command: 'systemctl status systemd-binfmt.service'"
  systemctl status systemd-binfmt.service
  echo "Still exiting with success, but you will have to manually run all x86 applications with box86 as binfmt isn't there to do it for you."
fi
