#!/bin/bash
rm -f ~/code.deb
wget -O ~/code.deb https://aka.ms/linux-arm64-deb || error 'Failed to download linux-arm64-deb!'
install_packages $HOME/code.deb || error 'Failed to install code.deb!'
rm -f ~/code.deb
