#!/bin/bash
rm -f ~/code.deb
wget -O ~/code.deb https://aka.ms/linux-armhf-deb || error 'Failed to download linux-armhf-deb!'
install_packages $HOME/code.deb || error 'Failed to install code.deb!'
rm -f ~/code.deb
